### ISSUE TITLE
[featrue/mypage_video] 무한 스크롤 범위 오류 

### ISSUE THREAD

**Issue by yeun38** [Final-healthree/healthree-frontend#14]
헤더 푸터 merge 이후 무한 스크롤 범위 오류 발생

**Comment by NickYOOO** [comment]
22년 9월 9일: 무한 스크롤이 레이아웃을 벗어나는 이슈가 있어 수정하는 작업에 들어가겠습니다. 
![스크린샷 2022-09-09 오후 3 03 34](https://user-images.githubusercontent.com/108923582/189284520-36806193-a1d9-4bf7-af34-22bc5778b490.png)

**Comment by NickYOOO** [comment]
22년 9월 9일: 라우터 컴포넌트 수정 그리고 css를 통해 수정완료.

- 기존 라우터에 레이아웃 밖으로 헤더와 풋터를 분리해 주었습니다.

(수정 전)
![스크린샷 2022-09-09 오후 4 52 48](https://user-images.githubusercontent.com/108923582/189311405-4c915d28-4d41-4982-95b9-8a2c9f217066.png)

(수정 후)
![스크린샷 2022-09-09 오후 4 52 34](https://user-images.githubusercontent.com/108923582/189311473-4032f3ac-6a67-441c-9a19-80728b0df19c.png)


 - 레이아웃 수정: height :100vh 값을 주었고, overflow-y: scroll; 값을 주어 동영상 페이지에 스크롤을 달아 주었습니다.
 
![스크린샷 2022-09-09 오후 4 52 16](https://user-images.githubusercontent.com/108923582/189311864-a7130780-61bb-407f-9202-5461593458fb.png)

 - 헤더와 풋터에 css 추가: 각각 width를 주어 길이를 조절하였고  중앙 정렬 left: 50%, transform: translateX(-50%);  상단 하단 끝 포지션 position: sticky; 를 주었습니다.
 
![스크린샷 2022-09-09 오후 4 53 20](https://user-images.githubusercontent.com/108923582/189312903-eb3325b4-f964-4769-9706-fd83e236bd60.png)

![스크린샷 2022-09-09 오후 4 53 13](https://user-images.githubusercontent.com/108923582/189312809-7fbe75e4-03a4-44b3-9fee-8eabbbf0d21e.png)

-  수정 완료
![스크린샷 2022-09-09 오후 5 55 43](https://user-images.githubusercontent.com/108923582/189312481-c71343fc-98b6-4559-818a-2b58ad6f440d.png)
